version: '3.8'
services:
  identity-api:
    build:
      context: ./
      dockerfile: ./services/identity/Identity.API/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Add connection strings/secrets as needed

  music-api:
    build:
      context: ./
      dockerfile: ./services/music/Music.API/Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  user-api:
    build:
      context: ./
      dockerfile: ./services/user/User.API/Dockerfile
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build: ./frontend/frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=spotibuds

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
  redis:
    image: redis:7
    ports:
      - "6379:6379"

      