name: CI/CD

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

env:
  REGISTRY: spotibuds.azurecr.io
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Identity API
      uses: docker/build-push-action@v5
      with:
        context: ./services/identity/Identity.API
        push: true
        tags: ${{ env.REGISTRY }}/identity-api:${{ env.IMAGE_TAG }}

    - name: Build and push Music API
      uses: docker/build-push-action@v5
      with:
        context: ./services/music/Music.API
        push: true
        tags: ${{ env.REGISTRY }}/music-api:${{ env.IMAGE_TAG }}

    - name: Build and push User API
      uses: docker/build-push-action@v5
      with:
        context: ./services/user/User.API
        push: true
        tags: ${{ env.REGISTRY }}/user-api:${{ env.IMAGE_TAG }}

    - name: Build and push Frontend
      uses: docker/build-push-action@v5
      with:
        context: ./frontend/frontend
        push: true
        tags: ${{ env.REGISTRY }}/frontend:${{ env.IMAGE_TAG }}

    # Deploy to Azure Web App for Containers using publish profiles
    - name: Deploy Identity API to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: identity-spotibuds
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_IDENTITY }}
        images: ${{ env.REGISTRY }}/identity-api:${{ env.IMAGE_TAG }}

    - name: Deploy Music API to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: music-spotibuds
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_MUSIC }}
        images: ${{ env.REGISTRY }}/music-api:${{ env.IMAGE_TAG }}

    - name: Deploy User API to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: user-spotibuds
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_USER }}
        images: ${{ env.REGISTRY }}/user-api:${{ env.IMAGE_TAG }}

    - name: Deploy Frontend to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: frontend-spotibuds
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FRONTEND }}
        images: ${{ env.REGISTRY }}/frontend:${{ env.IMAGE_TAG }}